import 'package:freezed_annotation/freezed_annotation.dart';
part 'all_char_response_model.g.dart';

@JsonSerializable()
class AllCharResponseModel {
  @JsonKey(name: 'results')
  List<AllChars>? allCharsList;

  AllCharResponseModel({this.allCharsList});

  factory AllCharResponseModel.fromJson(Map<String, dynamic> json) =>
      _$AllCharResponseModelFromJson(json);
}

@JsonSerializable()
class AllChars {
  int? id;
  String? name;
  String? image;

  AllChars({this.id, this.name, this.image});

  factory AllChars.fromJson(Map<String, dynamic> json) =>
      _$AllCharsFromJson(json);
}
// 3o : fromJson and toJson methods are generated by the json_serializable package